# This is a basic workflow that is manually triggered

name: compile osmosis

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request, workflow_dispatch]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    name: osmosis state sync
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with: 
          go-version: '^1.17'

      - name: Compile osmosis
        run: ./...
              
      - name: init
        run: |
          osmosisd init test
          wget -O ~/.osmosisd/config/genesis.json https://cloudflare-ipfs.com/ipfs/QmXRvBT3hgoXwwPqbK6a2sXUuArGM8wPyo1ybskyyUwUxs 

      - name: state sync
        run: bash scripts/statesync.sh