# This is a basic workflow that is manually triggered

name: Sync for an hour

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request, workflow_dispatch]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    name: osmosis sync performance
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with: 
          go-version: '^1.17'

      - name: Install Osmosis
        run: go install ./...
        
      - name: Install pm2
        run: npm install pm2 -g
      
        
      - name: Sync
        run: |
          osmosisd init test
          wget -O ~/.osmosisd/config/genesis.json https://cloudflare-ipfs.com/ipfs/QmXRvBT3hgoXwwPqbK6a2sXUuArGM8wPyo1ybskyyUwUxs 
          pm2 start "osmosisd start" 
          
      - name: 1 minute
        run: |
          sleep 60
          osmosisd status
          
      - name: 10 minutes
        run: |
          sleep 540
          osmosisd status
          
      
